import Head from 'next/head'

import Footer from '../components/Footer/Footer'
import HomeMain from '../components/HomeComponents/HomeMain'
import HomeContent from '../components/HomeComponents/HomeContent'
import Header from '../components/Header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <HomeContent />
        <HomeMain />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}
