import Head from 'next/head'
import Footer from '../components/Footer/Footer'
import HomeContent from '../components/HomeComponents/HomeContent'
import Header from '../components/Header/Header'
import Projects from '../components/ProjectsComponents/Projects'

const projects = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <HomeContent />
        <Projects />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default projects